name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read
  id-token: write  # Required for creating a release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Create Release Tag
      run: |
        # Get the latest commit hash
        COMMIT_HASH=$(git rev-parse --short HEAD)
        # Create a tag for the release
        TAG_NAME="v1.0.${COMMIT_HASH}"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./path/to/your/output/artifact # Adjust this to the path of your build artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
